//Objetos
    // let exeObj = {
    //     nr: 500,
    //     str: 'palavra'
    // };
    // console.log(exeObj.nr);

//Como criar objeto
    //Sintaxe
        // nomeObjeto = new construtor(argumento);
    //Exemplo
        // data=new Data();
        // let livro = new Object();

//Funções construtoras
    //Sintaxe
        // const carro = {
        //     marca:'Marca',
        //     preco: 0,
        // }
        // const honda = carro;
        // honda.marca = 'Honda';
        // honda.preco = 244000;

        // const nissan = carro;
        // nissan.marca = 'Nissan';
        // nissan.preco = 120000;

//Como iterar por um objeto
    //Sintaxe
        // for (variavel in objeto){...

        // }

    //Exemplo
        // let carro={
        //     portas: 4,
        //     rodas: 4,
        //     marcas: 'Um Carro',
        //     Avenda: true
        // };
        // for (let detalhes in carro){
        //     console.log(detalhes+':'+
        //         carro[detalhes]);
        // }

